application:
  server.port: 8086
  name: infra-gin
  auth.ignore:
    - "/sys/user/login$"
    - "^/api/public/"


# 日志配置
logrus:
  level: debug
  logFileName: infra-gin
  filePath: logs/
  #  配置日志切割
  # 30 * 24 * 60 * 60 一个月
  maxAge: 2592000
  # 24 * 60 * 60 一天
  rotationTime: 86400
